# Generated by Django 4.0.6 on 2022-08-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_remove_follow_unique_following_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='actors',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='keywords',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='related_shows',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='medium',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='poster',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
