# Generated by Django 4.0.6 on 2022-08-19 20:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_recommendation_actors_recommendation_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='actors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='genre',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='poster',
            field=models.URLField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='related_shows',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='streaming_service',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, null=True), null=True, size=None),
        ),
    ]
