# Generated by Django 4.0.6 on 2022-08-19 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_alter_recommendation_actors_and_more'),
        ('recommendations', '0005_remove_follow_follower-followed'),
    ]

    operations = [
    ]
