# Generated by Django 4.0.6 on 2022-08-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_alter_follow_followee_alter_follow_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='actors',
            field=models.JSONField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='genre',
            field=models.JSONField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='keywords',
            field=models.JSONField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='poster',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='related_shows',
            field=models.JSONField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='streaming_service',
            field=models.JSONField(max_length=200, null=True),
        ),
    ]
