# Generated by Django 4.0.6 on 2022-08-24 18:43

from django.db import migrations, models
import recommendations.models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0006_alter_recommendation_actors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImageTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=recommendations.models.nameFile)),
            ],
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='poster',
            field=models.JSONField(max_length=500, null=True),
        ),
    ]
