# Generated by Django 4.0.6 on 2022-08-29 15:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0007_user_image_alter_recommendation_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='emotion',
            field=models.JSONField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='watched_by',
            field=models.ManyToManyField(related_name='watches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='reason',
            field=models.TextField(max_length=2500),
        ),
    ]
