# Generated by Django 4.0.6 on 2022-08-27 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0008_recommendation_emotion_alter_recommendation_poster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='watched_by',
            field=models.ManyToManyField(blank=True, related_name='watches', to=settings.AUTH_USER_MODEL),
        ),
    ]
