# Generated by Django 4.0.6 on 2022-08-29 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0009_recommendation_watched_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='watched_by',
            field=models.ManyToManyField(related_name='watches', to=settings.AUTH_USER_MODEL),
        ),
    ]
